name: Build and Push Docker Image

on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Image
        file: ./Dockerfile
        run: |
          docker build ./app/ -t adamsetiaji/nodejs-manager:latest

      - name: Push Image Docker to Hub
        run: |
          docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker push adamsetiaji/nodejs-manager:latest
